### PR TITLE
Download path refactor

### PR DESCRIPTION
**Pull request by vigji**
So, I am moving my way from the beginning to understand the full library. I saw that the plan was to reformat os dependencies out of the package, so I tried to clean up the self-contained download module for this 

While doing it, I removed an argument that was passed to `download` only to print it, and I removed the `atlas` file, which was a bit confusing since there's another `atlas` module and an `Atlas` class from which one would instantiate `atlas` objects.

I noticed that the conf file does not get the correct resolution for the 100um dataset. I would be happy to fix this, but I want to be sure of what should be the aim with such file. Is it supposed to be kept in the module folder, and contain a keyword description for all the available atlases on the machine? right now it seems to support only one atlas, and if I download the 100um dataset it overwrites the location but does not update the resolution. Moreover, it can  keep one atlas only.

Why do you go with such config files and the line-by-line replacing? Why not using a json dictionary and append another element for a new atlas?

### CODE REVIEW

**Comment by adamltyson** [comment]
Thanks for this.

As with many things, the reasons are historical, the config file was originally used to specify registration parameters (that are now command-line arguments). It has lost much of its functionality, but what remains is:
1. To point amap to the installation directory of the atlas (if different to the default).
2. To allow for different kinds of atlases in the future (i.e. ones where we might not be able to get the voxel sizes from the metadata).
3. To achieve https://github.com/SainsburyWellcomeCentre/amap-python/issues/43

This needs to be rethought however, to properly support multiple atlases (i.e allow multiple atlases to be installed and switched between). The concept of a config file could just be removed by:
* Providing an atlas-specific config in the download.
* Copying the required data into the log file (see https://github.com/SainsburyWellcomeCentre/amap-python/issues/45) 

This however leaves `3` as an outstanding problem. Unless you have a better idea for pointing to the download directory, I think the single json dictionary and appending for each newly downloaded atlas idea is the best option.

**Comment by vigji** [comment]
I agree. Then in this pull request then I will give it a try to replace the current version with a json dictionary. 
However, in general, it's not so hard to require some minimal consistency in the references that would make this file redundant: .nii already have the resolution and the orientation; hemispheres numbers should be always  consistent and so names of the files in the folder. If this is the case, such config could be come just a dictionary of key:path

**Comment by adamltyson** [comment]
Yep. Just to say, down the line I would like to support atlases in other formats (i.e. not just nii), because: 
* I don't want to force people to interact with nii files to make an atlas
* There are plans to make amap interoperable with other software, and so the nii files will be just an intermediate step for niftyreg-specific registration, and the final output may be in tiff etc. cc @raacampbell

**Comment by vigji** [comment]
Makes sense! Well, that's just another entry in the hierarchical dictionary so no big deal

**Comment by vigji** [comment]
Also, instead of the separate resolution and orientation fields, we might want just the real world coordinates transformation matrix as specified in the .nii file - that takes care of resolution, orientation, and offsets

**Comment by adamltyson** [comment]
I'm not 100% sure the atlas nii files have the correct metadata, but that can be fixed. 

The whole orientation thing needs a bit of an overhall. It should be possible to do the atlas preprocessing given the atlas metadata, and a single parameter describing the orientation of the brain with respect to the input data array, rather than have multiple `--orientation saggital --flip-x` flags etc.

**Comment by vigji** [comment]
In principle, just specifying signs, numbers, and numbers positions in the (grid-to-world) affine matrix  of the .nii file should take care of that right? I am not familiar with niftyreg, but in the `dipy` library for example that can be quickly used to match the moving and reference images before starting the alignment.

**Comment by adamltyson** [comment]
Yes, I think theoretically we could use the information in the image headers and avoid reorienting the data. Other than time, the reasons I haven't looked into this approach are:
* The amount of downstream code that would need to be changed
* Users would need to use a viewer that was "aware" of the nifti headers. E.g I'm not sure that ImageJ for example would display data properly.

**Comment by vigji** [comment]
right now it seems that there's 2 atlases downloads happening: 1) the test one (the 100um one), saved to a temporary folder, and 2) the standard 100um one, located in /home/.amap/atlas.

To me it looks like ideally we want only one donwload - the 100 um for speed sake? - but to have this working in the test one would need to address more generally the trouble of passing an atlas different from the 10um one. I would give it a try if you want me to, in this or in a new PR.

**Comment by adamltyson** [comment]
Do you mean that both atlases are downloaded in the tests? Originally I wanted to make sure that the default (10um) atlas was always available, but it's not strictly necessary to be in the tests.

**Comment by adamltyson** [comment]
N.B. one issue with the tests is that the amap results vary between OS (very slightly). I'm not sure if this is due to the OS, or different versions of niftyreg.

So if you're tests are passing on windows, they may not pass on Travis (which is using ubuntu).

**Comment by vigji** [comment]
Yes, I am noticing that :D for some funny reason now it seems to fail even if I use your original volumes! Can you have a look into that? that seems to be the only problem now...

Probably if this is the case there should be more relaxed conditions on the testing, eg, setting a limit on the total difference between the two images

**Comment by adamltyson** [comment]
Yep, I'll look into:
* Compiling windows and linux versions identically
* If that doesn't fix it, having some less conservative tests.

**Comment by adamltyson** [comment]
P.S do you want to have a chat sometime about what your uses of amap etc. are, so we can better plan?

**Comment by adamltyson** [comment]
Also, this PR still shows that the test data has changed ...

**Comment by vigji** [comment]
I changed them 2 times: 1st, copying the files from the original master branch, because I thought I might have messed something there; 2nd, I copied the results of the transformation on my local machine, but that was again useless...but test was failing even with the upstream master files, unless I screwed something up

**Comment by vigji** [comment]
> P.S do you want to have a chat sometime about what your uses of amap etc. are, so we can better plan?

sure, dropping you an email :)

**Comment by vigji** [comment]
Finally got it! 😄 
I was replacing nii.get_data, apparently deprecated, with nii.get_fdata, which returns a float, and slightly changed registration results.
I guess this could be merged now! I will make it up for the tiny decrease in coverage :)

**Comment by adamltyson** [comment]
Looks good, but is `tests/data/registration_output/config.conf` added for a reason, or leftover from when you were editing the test data?

**Comment by vigji** [comment]
> Looks good, but is `tests/data/registration_output/config.conf` added for a reason, or leftover from when you were editing the test data?

leftover, I removed it now!

**Comment by vigji** [comment]
I wanted to address this 25-min long testing that comes from the downloading of the 10um atlas, but then I realised having only the 100um atlas around was producing some assertion error in the testing - are the results in the output folder obtained with the 10 or 100 atlas?

**Comment by adamltyson** [comment]
All the test results are with the 100um. The tests did originally download the 10um, but that's been removed (calling ` amap-python/tests/travis/testing.sh` not ` amap-python/tests/travis/testing_download.sh `)

**Comment by adamltyson** [comment]
The tests do take a long time on Travis though ...

**Comment by vigji** [comment]
I am almost 100% sure there's another spurious call to the download_atlas at 10 um resolution. Ok,  then I'll try to figure this out here before merging!

**Comment by vigji** [comment]
it seems that the `test_volume_calc` is still pointing to the 10um values, is this possible?

**Comment by adamltyson** [comment]
Yeah, that looks like a mistake. If the config file isn't being updated with the download of the 100um atlas, then the pixel sizes fetched in this function will be wrong.

**Comment by vigji** [comment]
Ok, i can try to have an ugly patch it to take the `test.conf` and then we can think of a general better solution once we cleanup this atlas configuration in `neuro`

**Comment by adamltyson** [comment]
Great.

FYI - `neuro` is still a bit of a mess, and is split between general whole-brain analysis functions, and some standalone tools. Feel free to refactor anything how you see fit.

**Comment by adamltyson** [comment]
Restarted the tests (one timed out).

**Comment by vigji** [comment]
ok, I think this can be merged now!

**Comment by adamltyson** [comment]
Awesome, thanks!

**Comment by vigji** [comment]
I refactored out the atlas submodule from the download module, this might cause an import problem in cellfinder!

**Comment by adamltyson** [comment]
Thanks. Fixed in https://github.com/SainsburyWellcomeCentre/cellfinder/commit/3ac3a2b4b8c72df1ce38b23c0a3fd0946c970bb5

**Pull request merged**
